import { useEffect, useMemo, useState } from "react";
import { api, uploadPhoto } from "./api";

const sections = ["Today", "Temperature Checks", "Deliveries", "Cleaning", "Opening / Closing", "Probe Calibration", "Corrective Actions", "Records / Audits", "Food Hygiene Settings"];
const correctionOptions = [["move_food", "Move food"], ["adjust_equipment", "Adjust equipment"], ["discard_food", "Discard affected food"], ["raise_action", "Raise Action / Defect"], ["other", "Other corrective action"]];

export function FoodHygiene({ boot, user }: { boot: any; user: any }) {
  const venueId = boot?.venues?.[0]?.id, query = venueId ? `?venue_id=${venueId}` : "";
  const [section,setSection]=useState("Today"),[today,setToday]=useState<any>(),[records,setRecords]=useState<any[]>([]),[equipment,setEquipment]=useState<any[]>([]),[active,setActive]=useState<any>(),[exception,setException]=useState<any>(),[message,setMessage]=useState("");
  const loadToday=()=>api<any>(`/food-hygiene/today${query}`).then(setToday), loadEquipment=()=>api<any[]>(`/food-hygiene/equipment${query}`).then(setEquipment);
  useEffect(()=>{if(venueId)void loadToday();},[venueId]);
  useEffect(()=>{if(section==="Temperature Checks"&&venueId)void loadEquipment();if(section==="Records / Audits"&&venueId)api<any[]>(`/food-hygiene/records${query}`).then(setRecords);},[section,venueId]);
  async function complete(task:any,status:string){const reason=status==="completed"?undefined:window.prompt(`Reason for ${status.replace("_"," ")}`);if(status!=="completed"&&!reason)return;await api(`/food-hygiene/tasks/${task.id}/complete`,{method:"POST",body:JSON.stringify({status,reason})});await loadToday();}
  async function recordTemperature(event:any){event.preventDefault();const form=event.currentTarget,data=Object.fromEntries(new FormData(form)),selected=equipment.find(x=>x.id===Number(data.equipment_id));try{const reading=await api<any>(`/food-hygiene/readings${query}`,{method:"POST",body:JSON.stringify({...data,photo:undefined,task_instance_id:active?.id||null,equipment_id:Number(data.equipment_id),recheck_of_id:exception?.id||null})});const photo=data.photo as File;if(photo?.size)await uploadPhoto("food_temperature_reading",reading.id,photo,false);if(!reading.compliant){setException({...reading,equipment_name:selected?.name});setMessage("");}else{setMessage(exception?"Recheck saved. The original exception remains in history.":"In-range reading saved.");setException(null);setActive(null);form.reset();await loadToday();}}catch(error){setMessage(error instanceof Error?error.message:"Reading could not be saved");}}
  const relevant=useMemo(()=>equipment.filter(x=>x.active&&(!active?true:active.title_snapshot.toLowerCase().includes("freezer")?x.equipment_type==="freezer":x.equipment_type!=="freezer")),[equipment,active]);
  const counts=today?.counts;
  return <div className="food-hygiene"><header className="pagehead"><div><p className="eyebrow">Compliance Hub · Food Hygiene</p><h1>{section==="Today"?"Today’s Food Hygiene":section}</h1><p>Fast, venue-authorised checks with immutable audit history</p></div></header><nav className="food-tabs" aria-label="Food Hygiene sections">{sections.map(x=><button key={x} className={section===x?"active":""} onClick={()=>setSection(x)}>{x}</button>)}</nav>{message&&<p className="food-message">{message}</p>}
    {section==="Today"&&<><div className="food-metrics"><Metric label="Checks due" value={counts?.due}/><Metric label="Complete" value={counts?.completed} tone="ok"/><Metric label="Outstanding" value={counts?.outstanding} tone="warn"/><Metric label="Overdue" value={counts?.overdue} tone="bad"/><Metric label="Unresolved temperature exceptions" value={counts?.unresolvedTemperatureExceptions} tone="bad"/><Metric label="Open corrective actions" value={counts?.openActions} tone="warn"/></div><TaskList tasks={today?.tasks||[]} complete={complete} open={(task:any)=>{setActive(task);setSection("Temperature Checks")}}/></>}
    {section==="Temperature Checks"&&<TemperatureForm active={active} equipment={relevant} exception={exception} submit={recordTemperature} resolve={async(type:string,notes:string)=>{await api(`/food-hygiene/readings/${exception.id}/corrective-action`,{method:"POST",body:JSON.stringify({corrective_action_type:type,notes})});setMessage("Corrective action recorded. The original exception remains in history.");setException(null);setActive(null);await loadToday();}}/>}
    {section==="Records / Audits"&&<section className="panel"><h2>Daily records</h2><div className="food-records">{records.map(r=><div key={r.id}><b>{r.due_date}</b><span>{r.title_snapshot}</span><span className={r.exception?"bad":""}>{r.status.replace("_"," ")}</span><small>{r.completed_by_name||"Not recorded"}{r.completed_at?` · ${new Date(r.completed_at).toLocaleString()}`:""}</small></div>)}</div></section>}
    {section==="Food Hygiene Settings"&&(user.role!=="administrator"?<section className="panel">Administrator access required.</section>:<Settings venueId={venueId} locations={boot?.locations||[]}/>)}
    {!["Today","Temperature Checks","Records / Audits","Food Hygiene Settings"].includes(section)&&<section className="panel"><h2>{section}</h2><p>Scheduled {section.toLowerCase()} appear on Today. Completed records remain available in Records / Audits.</p></section>}</div>;
}

function TemperatureForm({active,equipment,exception,submit,resolve}:{active:any;equipment:any[];exception:any;submit:(e:any)=>void;resolve:(type:string,notes:string)=>Promise<void>}){
  const [correction,setCorrection]=useState(""),[notes,setNotes]=useState("");
  if(exception)return <section className="temperature-warning" role="alert"><h2>Temperature outside configured range</h2><dl><div><dt>Equipment</dt><dd>{exception.equipment_name}</dd></div><div><dt>Recorded temperature</dt><dd>{exception.temperature} °C</dd></div><div><dt>Configured acceptable range</dt><dd>{exception.lower_limit_snapshot} °C to {exception.upper_limit_snapshot} °C</dd></div></dl><p>The task remains outstanding until a corrective action or satisfactory recheck is recorded.</p><h3>Recheck temperature</h3><form onSubmit={submit}><input type="hidden" name="reading_type" value={exception.reading_type}/><input type="hidden" name="equipment_id" value={exception.equipment_id}/><label>Immediate second reading °C<input name="temperature" type="number" inputMode="decimal" step="0.1" required/></label><label>Photo<input name="photo" type="file" accept="image/*" capture="environment"/></label><button>Save recheck</button></form><div className="correction"><h3>Or record corrective action</h3><label>Action<select value={correction} onChange={e=>setCorrection(e.target.value)}><option value="">Choose an action…</option>{correctionOptions.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder={correction==="other"?"Describe the corrective action":"Optional details"}/></label><button disabled={!correction||(correction==="other"&&!notes.trim())} onClick={()=>void resolve(correction,notes)}>Record corrective action</button></div></section>;
  return <section className="panel food-form"><h2>{active?.title_snapshot||"Refrigeration temperature checks"}</h2>{!equipment.length?<p>No active relevant refrigeration equipment is configured.</p>:<form onSubmit={submit}><label>Equipment<select name="equipment_id" required><option value="">Select unit…</option>{equipment.map(x=><option key={x.id} value={x.id}>{x.name} · {x.lower_limit} to {x.upper_limit} °C</option>)}</select></label><input type="hidden" name="reading_type" value={active?.title_snapshot?.toLowerCase().includes("freezer")?"freezer":"fridge"}/><label>Temperature °C<input name="temperature" type="number" inputMode="decimal" step="0.1" required/></label><label className="wide">Notes<textarea name="notes"/></label><label>Photo<input name="photo" type="file" accept="image/*" capture="environment"/></label><button>Check and save reading</button></form>}</section>;
}
function TaskList({tasks,complete,open}:{tasks:any[];complete:(t:any,s:string)=>void;open:(t:any)=>void}){return <section className="food-task-list">{tasks.map(task=><article key={task.id} className={`food-task ${task.status} ${task.exception?"exception":""}`}><div><span>{task.category_snapshot}</span><h2>{task.title_snapshot}</h2><p>{task.instructions_snapshot}</p><small>{task.status.replace("_"," ")}</small></div>{task.status==="outstanding"&&<div className="food-actions">{task.task_type_snapshot==="temperature"?<button onClick={()=>open(task)}>Record temperatures</button>:<button onClick={()=>void complete(task,"completed")}>Done</button>}<button className="secondary" onClick={()=>void complete(task,"skipped")}>Skip today</button><button className="secondary" onClick={()=>void complete(task,"not_applicable")}>Not applicable</button></div>}</article>)}</section>}
function Metric({label,value,tone=""}:{label:string,value:any,tone?:string}){return <article className={tone}><span>{label}</span><strong>{value??"–"}</strong></article>}

function Settings({venueId,locations}:{venueId:number;locations:any[]}){
  const query=`?venue_id=${venueId}&include_inactive=1`,[equipment,setEquipment]=useState<any[]>([]),[editing,setEditing]=useState<any>();const load=()=>api<any[]>(`/food-hygiene/equipment${query}`).then(setEquipment);useEffect(()=>{void load();},[venueId]);
  async function save(e:any){e.preventDefault();const form=e.currentTarget,d=Object.fromEntries(new FormData(form));await api(editing?`/food-hygiene/equipment/${editing.id}`:"/food-hygiene/equipment",{method:editing?"PATCH":"POST",body:JSON.stringify({...d,...(!editing&&{venue_id:venueId}),location_id:d.location_id||null,active:Number(d.active)})});setEditing(null);form.reset();await load();}
  return <><nav className="settings-subnav"><b>Refrigeration Equipment</b></nav><section className="panel"><h2>Refrigeration Equipment</h2><p>Only active units appear in new temperature checks. Limits are configured per unit.</p><div className="equipment-grid">{equipment.map(x=><article key={x.id} className={!x.active?"inactive":""}><h3>{x.name}</h3><p>{x.equipment_type} · {x.location_name||"No location"}</p><b>{x.lower_limit} °C to {x.upper_limit} °C</b><small>{x.active?"Active":"Inactive"}</small><button className="secondary" onClick={()=>setEditing(x)}>Edit</button></article>)}</div></section><section className="panel food-form"><h2>{editing?`Edit ${editing.name}`:"Add refrigeration unit"}</h2><form key={editing?.id||"new"} onSubmit={save}><label>Name<input name="name" required defaultValue={editing?.name}/></label><label>Type<select name="equipment_type" defaultValue={editing?.equipment_type||"fridge"}>{["fridge","freezer","chilled display","cold room","other"].map(x=><option key={x}>{x}</option>)}</select></label><label>Location<select name="location_id" defaultValue={editing?.location_id||""}><option value="">No location</option>{locations.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Status<select name="active" defaultValue={editing?.active??1}><option value="1">Active</option><option value="0">Inactive</option></select></label><label>Minimum acceptable °C<input name="lower_limit" type="number" step="0.1" required defaultValue={editing?.lower_limit}/></label><label>Maximum acceptable °C<input name="upper_limit" type="number" step="0.1" required defaultValue={editing?.upper_limit}/></label><label className="wide">Notes<textarea name="notes" defaultValue={editing?.notes}/></label><button>{editing?"Save changes":"Add unit"}</button>{editing&&<button type="button" className="secondary" onClick={()=>setEditing(null)}>Cancel</button>}</form></section></>;
}
