import { useEffect, useState } from "react";
import { api } from "./api";

const sections = ["Today", "Temperature Checks", "Deliveries", "Cleaning", "Opening / Closing", "Probe Calibration", "Corrective Actions", "Records / Audits", "Food Hygiene Settings"];

export function FoodHygiene({ boot, user }: { boot: any; user: any }) {
  const venueId = boot?.venues?.[0]?.id;
  const [section,setSection]=useState("Today"),[today,setToday]=useState<any>(),[settings,setSettings]=useState<any>(),[records,setRecords]=useState<any[]>([]),[active,setActive]=useState<any>(),[equipment,setEquipment]=useState<any[]>([]),[message,setMessage]=useState("");
  const query = venueId ? `?venue_id=${venueId}` : "";
  const loadToday=()=>api<any>(`/food-hygiene/today${query}`).then(setToday);
  useEffect(()=>{if(venueId)void loadToday();},[venueId]);
  useEffect(()=>{if(section==="Temperature Checks"&&venueId)api<any[]>(`/food-hygiene/equipment${query}`).then(setEquipment);if(section==="Records / Audits"&&venueId)api<any[]>(`/food-hygiene/records${query}`).then(setRecords);if(section==="Food Hygiene Settings"&&venueId&&user.role==="administrator")api<any>(`/food-hygiene/settings${query}`).then(setSettings);},[section,venueId]);
  async function complete(task:any,status:string){const reason=status==="completed"?undefined:window.prompt(`Reason for ${status.replace("_"," ")}`);if(status!=="completed"&&!reason)return;await api(`/food-hygiene/tasks/${task.id}/complete`,{method:"POST",body:JSON.stringify({status,reason})});await loadToday();}
  async function recordTemperature(event:any){event.preventDefault();const form=event.currentTarget,data=Object.fromEntries(new FormData(form));try{await api(`/food-hygiene/readings${query}`,{method:"POST",body:JSON.stringify({...data,task_instance_id:active?.id||null,equipment_id:data.equipment_id||null,create_action:true})});setMessage("Reading saved with user and time recorded.");setActive(null);form.reset();await loadToday();}catch(error){setMessage(error instanceof Error?error.message:"Reading could not be saved");}}
  const counts=today?.counts;
  return <div className="food-hygiene">
    <header className="pagehead"><div><p className="eyebrow">Compliance Hub · Food Hygiene</p><h1>{section==="Today"?"Today’s Food Hygiene":section}</h1><p>Fast, venue-authorised checks with immutable audit history</p></div></header>
    <nav className="food-tabs" aria-label="Food Hygiene sections">{sections.map(x=><button key={x} className={section===x?"active":""} onClick={()=>setSection(x)}>{x}</button>)}</nav>
    {message&&<p className="food-message">{message}</p>}
    {section==="Today"&&<>
      <div className="food-metrics"><Metric label="Checks due" value={counts?.due}/><Metric label="Complete" value={counts?.completed} tone="ok"/><Metric label="Outstanding" value={counts?.outstanding} tone="warn"/><Metric label="Overdue" value={counts?.overdue} tone="bad"/><Metric label="Exceptions" value={counts?.exceptions} tone="bad"/><Metric label="Open corrective actions" value={counts?.openActions} tone="warn"/></div>
      <section className="food-task-list">{today?.tasks?.map((task:any)=><article key={task.id} className={`food-task ${task.status} ${task.exception?"exception":""}`}><div><span>{task.category_snapshot}</span><h2>{task.title_snapshot}</h2><p>{task.instructions_snapshot}</p><small>{task.due_at?new Date(task.due_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"}):"Due today"} · {task.status.replace("_"," ")}</small></div>{task.status==="outstanding"&&<div className="food-actions">{task.task_type_snapshot==="temperature"?<button onClick={()=>{setActive(task);setSection("Temperature Checks")}}>Record temperature</button>:<button onClick={()=>void complete(task,"completed")}>Done</button>}<button className="secondary" onClick={()=>void complete(task,"skipped")}>Skip today</button><button className="secondary" onClick={()=>void complete(task,"not_applicable")}>Not applicable</button></div>}</article>)}</section>
    </>}
    {section==="Temperature Checks"&&<section className="panel food-form"><h2>{active?.title_snapshot||"Quick temperature record"}</h2><form onSubmit={recordTemperature}><label>Type<select name="reading_type" defaultValue={active?.title_snapshot?.toLowerCase().includes("freezer")?"freezer":"fridge"}><option value="fridge">Fridge</option><option value="freezer">Freezer</option><option value="cooking">Cooking</option><option value="other">Other</option></select></label><label>Equipment<select name="equipment_id"><option value="">Product / no equipment</option>{equipment.filter(x=>x.active).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Product<input name="product" autoComplete="off"/></label><label>Temperature °C<input name="temperature" type="number" inputMode="decimal" step="0.1" required autoFocus/></label><label className="wide">Notes / corrective action<textarea name="corrective_action" placeholder="Required if the configured range is missed"/></label><button>Save reading</button></form><p>Configured equipment or task limits are evaluated automatically. No legal limits are hard-coded.</p></section>}
    {section==="Records / Audits"&&<section className="panel"><h2>Daily records</h2><div className="food-records">{records.map(r=><div key={r.id}><b>{r.due_date}</b><span>{r.title_snapshot}</span><span className={r.exception?"bad":""}>{r.status.replace("_"," ")}</span><small>{r.completed_by_name||"Not recorded"}{r.completed_at?` · ${new Date(r.completed_at).toLocaleString()}`:""}</small></div>)}</div></section>}
    {section==="Food Hygiene Settings"&&(user.role!=="administrator"?<section className="panel">Administrator access required.</section>:<Settings data={settings} venueId={venueId} reload={()=>api<any>(`/food-hygiene/settings${query}`).then(setSettings)}/>)}
    {!["Today","Temperature Checks","Records / Audits","Food Hygiene Settings"].includes(section)&&<section className="panel"><h2>{section}</h2><p>Scheduled {section.toLowerCase()} appear on Today. Completed and exception records remain available in Records / Audits.</p>{today?.tasks?.filter((x:any)=>x.category_snapshot===section).map((x:any)=><button className="food-shortcut" onClick={()=>setSection("Today")} key={x.id}>{x.title_snapshot} · {x.status}</button>)}</section>}
  </div>;
}
function Metric({label,value,tone=""}:{label:string,value:any,tone?:string}){return <article className={tone}><span>{label}</span><strong>{value??"–"}</strong></article>}
function Settings({data,venueId,reload}:{data:any;venueId:number;reload:()=>void}){return <><section className="panel"><h2>Task templates</h2><div className="food-records">{data?.templates?.map((t:any)=><div key={t.id}><b>{t.title}</b><span>{t.category} · {t.frequency}</span><span>{t.active?"Active":"Inactive"}</span></div>)}</div></section><section className="panel"><h2>Add task template</h2><form className="gridform" onSubmit={async(e:any)=>{e.preventDefault();const f=e.currentTarget,d=Object.fromEntries(new FormData(f));await api("/food-hygiene/templates",{method:"POST",body:JSON.stringify({...d,venue_id:venueId})});f.reset();reload();}}><label>Title<input name="title" required/></label><label>Key<input name="template_key" pattern="[a-z0-9-]+" required/></label><label>Category<input name="category" required/></label><label>Type<select name="task_type"><option value="checklist">Checklist</option><option value="temperature">Temperature</option><option value="delivery">Delivery</option><option value="cleaning_checklist">Cleaning checklist</option><option value="calibration">Calibration</option><option value="cooling">Cooling</option></select></label><label>Frequency<select name="frequency"><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="as-needed">Unscheduled</option></select></label><label>Scheduled time<input name="scheduled_time" type="time"/></label><label>Lower configured limit<input name="lower_limit" type="number" step="0.1"/></label><label>Upper configured limit<input name="upper_limit" type="number" step="0.1"/></label><label className="wide">Instructions<textarea name="instructions"/></label><button>Add editable template</button></form></section><section className="panel"><h2>Registers</h2><p>{data?.equipment?.length||0} refrigeration units · {data?.probes?.length||0} probes · {data?.suppliers?.length||0} suppliers</p></section></>}
