(function(){'use strict';
var room=VL_ROOM_ID,origin=VL_SERVER_ORIGIN.replace(/\/$/,''),preview=typeof tizen==='undefined';
if(preview){var match=location.search.match(/[?&]room=([1-6])(?:&|$)/);if(match)room=Number(match[1]);}
var url=origin+'/api/tv/rooms/'+room+'/content',cacheKey='vl-cloud-room-'+room,data=null,view='welcome',selected=0,busy=false;
var buttons=document.getElementById('nav').getElementsByTagName('button'),panel=document.getElementById('content'),status=document.getElementById('status');
function node(tag,value,cls){var e=document.createElement(tag);e.textContent=value||'';if(cls)e.className=cls;return e;}
function message(title,text){panel.appendChild(node('h2',title));panel.appendChild(node('p',text));}
function focus(i){selected=(i+buttons.length)%buttons.length;buttons[selected].focus();}
function render(){var scroll=panel.scrollTop;while(panel.firstChild)panel.removeChild(panel.firstChild);if(!data){message('Make yourself at home','Hotel information is temporarily unavailable. Please speak to our team.');return;}document.getElementById('welcome').textContent='Welcome to '+data.room.label;
if(view==='welcome')message(data.pages[0].title,data.pages[0].text);
else if(view==='dining'){message('Dining at The Village Limits',data.contact.openingHours);data.menus.forEach(function(menu){panel.appendChild(node('h2',menu.name));if(menu.description)panel.appendChild(node('p',menu.description));menu.sections.forEach(function(section){panel.appendChild(node('h3',section.name));section.items.forEach(function(item){var row=node('div','','item');row.appendChild(node('span',item.price,'price'));row.appendChild(node('strong',item.name));row.appendChild(node('p',item.description,'description'));if(item.allergens)row.appendChild(node('p','Allergens: '+item.allergens,'allergens'));panel.appendChild(row);});});});if(!data.menus.length)panel.appendChild(node('p','Please ask our team about current menus.'));}
else if(view==='events'){panel.appendChild(node('h2',"What's on"));data.events.forEach(function(event){panel.appendChild(node('h3',event.title));panel.appendChild(node('p',[event.date||event.startDate,event.description,event.soldOut?'Currently sold out':event.price].filter(Boolean).join('\n')));});if(!data.events.length)panel.appendChild(node('p','Please ask our team about forthcoming events.'));}
else if(view==='movies')message('Movies / Airtime',preview?'Airtime opens on a compatible hotel TV. Movie playback is not available in this browser preview.':'Select Movies / Airtime again to open the installed movie app.');
else message('Hotel information',[data.contact.openingHours,data.contact.telephone?'Telephone: '+data.contact.telephone:'','Menus and events: www.villagelimits.co.uk'].filter(Boolean).join('\n\n'));
panel.scrollTop=scroll;}
function launchMovies(){if(preview){render();return;}try{tizen.application.getAppsInfo(function(apps){var id=null;for(var i=0;i<apps.length;i++)if(apps[i].name.toLowerCase()==='airtime'){id=apps[i].id;break;}if(!id){status.textContent='Airtime is not installed on this TV.';return;}tizen.application.launch(id,function(){},function(e){status.textContent='Unable to open Airtime: '+e.name;});},function(e){status.textContent='Unable to find Airtime: '+e.name;});}catch(e){status.textContent='Unable to open Airtime: '+e.message;}}
function open(i){focus(i);view=buttons[i].getAttribute('data-view');panel.scrollTop=0;render();if(view==='movies')launchMovies();}
for(var i=0;i<buttons.length;i++)(function(index){buttons[index].onclick=function(){open(index);};})(i);
document.addEventListener('keydown',function(e){var k=e.keyCode;if(k===37||k===39){focus(selected+(k===37?-1:1));e.preventDefault();}else if(k===38||k===40){panel.scrollTop+=(k===38?-1:1)*130;e.preventDefault();}else if(k===13){open(selected);e.preventDefault();}else if(k===10009||k===27||k===8){open(0);e.preventDefault();}});
function valid(value){return value&&value.schemaVersion===1&&value.room&&value.room.id===room&&Array.isArray(value.pages)&&value.pages.length===3&&value.pages.every(function(p){return typeof p.title==='string'&&typeof p.text==='string';})&&Array.isArray(value.menus)&&Array.isArray(value.events)&&value.contact;}
function poll(){if(busy)return;busy=true;var xhr=new XMLHttpRequest();xhr.open('GET',url+'?v='+Date.now()+(preview?'&preview=1':''),true);xhr.timeout=10000;function failed(){busy=false;status.textContent=data?'Offline · showing saved hotel information':'Hotel information unavailable · retrying automatically';}xhr.onerror=failed;xhr.ontimeout=failed;xhr.onload=function(){busy=false;try{if(xhr.status===404){data=null;try{localStorage.removeItem(cacheKey);}catch(ignore){}status.textContent='Cloud content is not enabled for this room.';render();return;}if(xhr.status!==200)throw Error('HTTP '+xhr.status);var next=JSON.parse(xhr.responseText);if(!valid(next))throw Error('Invalid hotel content');var changed=!data||data.revision!==next.revision;data=next;try{localStorage.setItem(cacheKey,JSON.stringify(data));}catch(ignore){}status.textContent='Content received · '+new Date().toLocaleTimeString();if(changed)render();}catch(e){failed();}};try{xhr.send();}catch(e){failed();}}
try{var cached=JSON.parse(localStorage.getItem(cacheKey));if(valid(cached)){data=cached;status.textContent='Showing saved hotel information · connecting…';}}catch(ignore){}
focus(0);render();poll();setInterval(poll,30000);document.addEventListener('visibilitychange',function(){if(!document.hidden){open(0);poll();}});
})();
